### ISSUE TITLE
Add Ticket model to Nutuella's back-end app

### ISSUE THREAD

**Issue by gil27** [gil27/nutella#4]
Tickets should contain:

- name
- body
- author's email
- status (open, doing, closed)

**Comment by sashamussich** [comment]
Tickets or issues :)

**Comment by gil27** [comment]
@sashamussich I'm sorry. I completely forgot.

I kept the ticket name on my mind. Do you think it's possible to change it to be issue?

**Comment by gil27** [comment]
@sashamussich I've renamed the model and tests to Issue. You can check it out on PR https://github.com/gil27/nutella/pull/10
